/**
 * build-data.js
 *
 * Runs automatically on every Cloudflare Pages build (see cloudflare build
 * command). It does two jobs:
 *
 * 1. IMAGE PROCESSING
 *    For every travel folder under assets/img/<ordner>/, looks inside an
 *    "incoming" subfolder for newly dropped photos (any format, any size,
 *    any filename). Each one gets resized (max width 2200px) and converted
 *    to WebP, then renamed to the next free "<praefix>-XXXX.webp" slot in
 *    the main folder. The original file in "incoming" is then deleted.
 *
 * 2. DATA GENERATION
 *    Reads every content/reisen/*.json file (one per trip) plus
 *    content/favoriten.json, counts how many "<praefix>-XXXX.webp" files
 *    now exist in each trip's folder, and writes the final
 *    assets/js/reisen-data.js that the website actually uses.
 *
 * Result: dropping raw photos into an "incoming" folder and pushing to
 * GitHub is the only manual step needed. No file sizes, formats, or photo
 * counts need to be edited by hand anywhere.
 */

const fs = require("fs");
const path = require("path");
const sharp = require("sharp");

const ROOT = path.join(__dirname);
const CONTENT_REISEN_DIR = path.join(ROOT, "content", "reisen");
const FAVORITEN_PATH = path.join(ROOT, "content", "favoriten.json");
const IMG_DIR = path.join(ROOT, "assets", "img");
const OUTPUT_PATH = path.join(ROOT, "assets", "js", "reisen-data.js");

const MAX_WIDTH = 2200;
const WEBP_QUALITY = 88;
const SUPPORTED_INPUT_EXT = [".jpg", ".jpeg", ".png", ".heic", ".webp", ".tif", ".tiff"];

function log(msg) {
  console.log(`[build-data] ${msg}`);
}

// ---------- Step 1: process "incoming" photos for a single trip ----------
async function processIncoming(ordner, praefix) {
  const folderPath = path.join(IMG_DIR, ordner);
  const incomingPath = path.join(folderPath, "incoming");

  if (!fs.existsSync(incomingPath)) return; // nothing to do for this trip

  const incomingFiles = fs
    .readdirSync(incomingPath)
    .filter((f) => SUPPORTED_INPUT_EXT.includes(path.extname(f).toLowerCase()))
    .sort(); // stable order, e.g. by filename/date if named IMG_0001, IMG_0002...

  if (incomingFiles.length === 0) return;

  // Find the highest existing index already used, e.g. vienna-0007.webp -> 7
  const existing = fs.existsSync(folderPath)
    ? fs.readdirSync(folderPath)
    : [];
  const pattern = new RegExp(`^${escapeRegExp(praefix)}-(\\d{4})\\.webp$`);
  let highestIndex = 0;
  for (const file of existing) {
    const match = file.match(pattern);
    if (match) {
      highestIndex = Math.max(highestIndex, parseInt(match[1], 10));
    }
  }

  log(`${ordner}: found ${incomingFiles.length} new photo(s) in incoming/, starting at index ${highestIndex + 1}`);

  for (const file of incomingFiles) {
    highestIndex += 1;
    const nummer = String(highestIndex).padStart(4, "0");
    const inputPath = path.join(incomingPath, file);
    const outputPath = path.join(folderPath, `${praefix}-${nummer}.webp`);

    await sharp(inputPath)
      .rotate() // auto-orient based on EXIF (important for phone photos)
      .resize({ width: MAX_WIDTH, withoutEnlargement: true })
      .webp({ quality: WEBP_QUALITY })
      .toFile(outputPath);

    fs.unlinkSync(inputPath);
    log(`  -> ${file} => ${praefix}-${nummer}.webp`);
  }
}

function escapeRegExp(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// ---------- Step 2: count final photos for a trip ----------
function countPhotos(ordner, praefix) {
  const folderPath = path.join(IMG_DIR, ordner);
  if (!fs.existsSync(folderPath)) return 0;

  const pattern = new RegExp(`^${escapeRegExp(praefix)}-(\\d{4})\\.webp$`);
  const files = fs.readdirSync(folderPath).filter((f) => pattern.test(f));
  return files.length;
}

// ---------- Main ----------
async function main() {
  if (!fs.existsSync(CONTENT_REISEN_DIR)) {
    console.error(`Missing folder: ${CONTENT_REISEN_DIR}`);
    process.exit(1);
  }

  const reisenFiles = fs
    .readdirSync(CONTENT_REISEN_DIR)
    .filter((f) => f.endsWith(".json"))
    .sort();

  const reisen = [];

  for (const file of reisenFiles) {
    const filePath = path.join(CONTENT_REISEN_DIR, file);
    const data = JSON.parse(fs.readFileSync(filePath, "utf-8"));

    if (!data.ordner || !data.praefix) {
      console.error(`Trip file ${file} is missing "ordner" or "praefix" - skipping`);
      continue;
    }

    await processIncoming(data.ordner, data.praefix);
    const anzahl = countPhotos(data.ordner, data.praefix);

    reisen.push({ ...data, anzahl });
    log(`${data.id}: ${anzahl} photo(s) total`);
  }

  const favoriten = fs.existsSync(FAVORITEN_PATH)
    ? JSON.parse(fs.readFileSync(FAVORITEN_PATH, "utf-8"))
    : [];

  const output = `/**
 * AUTO-GENERATED FILE - do not edit by hand.
 * Generated by build-data.js from content/reisen/*.json and content/favoriten.json.
 * Run "npm run build:data" (or let Cloudflare Pages run it automatically) to regenerate.
 */

const reisen = ${JSON.stringify(reisen, null, 2)};

const favoriten = ${JSON.stringify(favoriten, null, 2)};
`;

  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
  fs.writeFileSync(OUTPUT_PATH, output, "utf-8");
  log(`Wrote ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});